"""The ``cluster-exec`` wrapper — run a command inside the agent image on a compute node.

``write_cluster_exec()`` writes a small shell script into the launch's workdir.
A job script submitted from the agent's container calls it (by absolute host
path, via ``$CLUSTER_EXEC``) to run its command inside ``apptainer exec``
against the same image, with the cluster scratch bound at the same path it has
on the host and in the container. That side-steps "the compute node has no
MadGraph / no sfitter": the job sees the image's software, and every path under
the scratch means the same thing everywhere.
"""
from __future__ import annotations

import shlex
from pathlib import Path

_CLUSTER_EXEC_TEMPLATE = """\
#!/bin/bash
# Generated by the SFitterAgents launcher. Runs a command inside the agent image
# on a compute node, with the cluster scratch ({cluster_runs_path}) bound at the
# same path it has on the host and in the agent's container.
#
# Usage from a job script:
#   {script_path} <command> [args...]
# $CLUSTER_EXEC in the agent's container holds this path. It is not forwarded to
# the job, so expand it when writing the job script (unquoted heredoc).
#
# The image and the tmpfs are the only filesystems besides the binds: anything a
# job must keep goes under the cluster scratch. The MAD venv is activated before
# the command — the image's %environment sets VIRTUAL_ENV but does not put the
# venv on PATH, and without it mg5_aMC resolves to the system python (no six).
set -e
# A private scratch dir per job on node-local disk (mode 0700, unpredictable
# name, removed at exit): apptainer's session dir and /tmp go there, so
# incidental writes do not fill the in-memory --writable-tmpfs layer, and it
# holds the job's own $HOME, so per-user tool state (~/.mg5, ...) never collides
# across jobs.
SCR=$(mktemp -d "${{TMPDIR:-/tmp}}/sfitteragents-job.XXXXXXXX")
trap 'rm -rf "$SCR"' EXIT
mkdir "$SCR/home"
EXTRA=()
# Site facts, when the site provides them and the node can see them.
[ -d {internals_path} ] && EXTRA+=(--bind {internals_path}:/internals:ro)
# --cleanenv drops the scheduler's GPU assignment; hand it over explicitly.
[ -n "${{CUDA_VISIBLE_DEVICES:-}}" ] && EXTRA+=(--env "CUDA_VISIBLE_DEVICES=$CUDA_VISIBLE_DEVICES")
# --nv makes the node's NVIDIA driver available (SFitter fits run on the GPU);
# on a node without one apptainer only warns.
{apptainer_bin} exec \\
    --cleanenv \\
    --nv \\
    --workdir "$SCR" \\
    --writable-tmpfs \\
    --bind {cluster_runs_path}:{cluster_runs_path} \\
    --bind "$SCR/home":/jobhome \\
    "${{EXTRA[@]}}" \\
    {image} \\
    bash -c 'export HOME=/jobhome; . /opt/envs/MAD/bin/activate 2>/dev/null || true; exec "$@"' _ "$@"
"""


def write_cluster_exec(
    *,
    script_path: Path,
    apptainer_bin: Path,
    image: Path,
    cluster_runs_path: Path,
    internals_path: Path | None,
) -> Path:
    """Write a launch's ``cluster-exec`` script and make it executable.

    *script_path* is the host path the script lives at, inside the cluster
    scratch: the compute node runs it by that exact path over the shared
    filesystem, and the container sees it at the same path through the scratch
    bind (and at ``/usr/local/bin/cluster-exec``). The image and the apptainer
    binary are referenced by absolute host path, so compute nodes must reach
    them at the same paths.
    """
    # A job binds /internals only if the directory exists on the node that runs it.
    internals_arg = str(internals_path) if internals_path is not None else "/nonexistent"
    script_path.write_text(_CLUSTER_EXEC_TEMPLATE.format(
        apptainer_bin=shlex.quote(str(apptainer_bin)),
        image=shlex.quote(str(image)),
        cluster_runs_path=shlex.quote(str(cluster_runs_path)),
        internals_path=shlex.quote(internals_arg),
        script_path=str(script_path),
    ))
    script_path.chmod(0o755)
    return script_path
